#!/usr/bin/env python3

import getpass
import sys
import telnetlib

HOST = "192.168.1.1"
user = raw_input("Enter your username: ")
password = getpass.getpass()

tn = telnetlib.Telnet(HOST)

tn.read_until("Username: ")
tn.write(user + "\n")
if password:
    tn.read_until("Password: ")
    tn.write(password + "\n")

tn.write("conf t\n")

for n in range (2,10):
	tn.write("vlan " + str(n) + "\n")
	tn.wirte("name autoVLAN_" + str(n) + "\n")


print tn.read_all()

